name: deploy

on:
  workflow_run:
    workflows: ["check"]
    branches: [main]
    types:
      - completed
  # schedule:
    # - cron: "0 18 * * 4"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.passing.outputs.build_id }}
    steps:
      - name: Wait for check workflows_run to succeed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: exit 1
      - name: Go On
        if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
        run: |
          git config --global --add safe.directory $(pwd)
          git clone --quiet https://${{ github.token }}@github.com/${{ github.repository }} .
          ref=$(echo ${{ github.ref }} | sed -E -n -e 's/^refs\/[^/]*\/(.*)$/\1/p')
          git checkout $ref
        shell: bash
      - name: Checkout
        uses: ./.github/checkout
      - name: Prearing
        uses: ./.github/heroku-build
        with:
          app-name: "${{secrets.APP}}"
          api-key: "${{secrets.KEY}}"
      - name: Build
        id: passing
        run: |
          sleep 400
          echo "::set-output name=build_id::$BUILD_ID"
  
  deploy:
    needs: build 
    runs-on: ubuntu-latest
    if:  ${{ success() }}
    steps:
      - name: clone repo
        run: |
            git config --global --add safe.directory $(pwd)
            git clone --quiet https://${{ github.token }}@github.com/${{ github.repository }} .
            ref=$(echo ${{ github.ref }} | sed -E -n -e 's/^refs\/[^/]*\/(.*)$/\1/p')
            git checkout $ref
        shell: bash
      
      - name: checkout
        id: checkout
        uses: ./.github/checkout
      
      - name: build
        run: echo ğŸ‘‹ğŸ‘ğŸ‘ğŸ‘ SUCCESS ğŸ‘‹ğŸ‘ğŸ‘ğŸ‘! ${{ needs.build.outputs.build_id }}
      
      - name: deploy
        if:  ${{ success() }}
        uses: ./.github/heroku-deploy 
        with:
          heroku_api_key: ${{ secrets.KEY }}
          heroku_app_name: ${{ secrets.APP }}
          heroku_email: ${{ secrets.MAIL }}
